trigger: none
pr: none

jobs:
- job: Build
  pool: 'Edge-Robotics-VS2019'
  #  vmImage: 'windows-2019'
  timeoutInMinutes: 360
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific' # Options: current, specific
      project: 'ros-win' # Required when source == Specific
      pipeline: 91 # Required when source == Specific
      buildVersionToDownload: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
      artifactName: 'foxy-drop'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)\foxy-drop\*.zip' 
      destinationFolder: 'c:\opt\ros\foxy\x64'
      cleanDestinationFolder: true
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      copy /Y experimental\ros\python38._pth c:\opt\ros\foxy\x64\python38._pth
      copy /Y experimental\ros\extra.pth c:\opt\ros\foxy\x64\Lib\site-packages
      dir c:\opt\ros\foxy\x64
      set PATH=c:\opt\ros\foxy\x64\Scripts;c:\opt\ros\foxy\x64;c:\opt\ros\foxy\x64\bin;%PATH%
      mkdir catkin_ws\src
      cd catkin_ws
      :: vcs import src < ..\experimental\ros\gazebo.rosinstall
      python -m site
      vcs import src < ..\experimental\ros\ros2.repos
      dir src
      DEL /F /Q C:\opt\ros\foxy\x64\share\tinyxml\tinyxml-config.cmake
      DEL /F /Q C:\opt\ros\foxy\x64\share\tinyxml\tinyxmlTargets-release.cmake
      DEL /F /Q C:\opt\ros\foxy\x64\share\tinyxml\tinyxmlTargets.cmake
      colcon build --cmake-args -DCURL_NO_CURL_CMAKE=ON -DBUILD_TESTING:BOOL=False -DCMAKE_PROGRAM_PATH=c:\opt\ros\foxy\x64\tools\protobuf;c:\opt\ros\foxy\x64\tools\qt5\bin
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: .\catkin_ws\log
      artifactName: log
    condition: always()
