trigger: none
pr: none

jobs:
- job: Build
  pool: 'Edge-Robotics-VS2019'
  #  vmImage: 'windows-2019'
  strategy:
    matrix:
      noetic:
        INSTALL_DIR: 'c:\opt\ros\noetic\x64'
        DISTRO_NAME: 'noetic'
      foxy:
        INSTALL_DIR: 'c:\opt\ros\foxy\x64'
        DISTRO_NAME: 'foxy'
  timeoutInMinutes: 360
  workspace:
    clean: all
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific' # Options: current, specific
      project: 'ros-win' # Required when source == Specific
      pipeline: 91 # Required when source == Specific
      buildVersionToDownload: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
      artifactName: '$(DISTRO_NAME)-drop'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)\$(DISTRO_NAME)-drop\*.zip' 
      destinationFolder: '$(INSTALL_DIR)'
      cleanDestinationFolder: true
  - script: |
      DEL /F /Q %INSTALL_DIR%\share\tinyxml\tinyxml-config.cmake
      DEL /F /Q %INSTALL_DIR%\share\tinyxml\tinyxmlTargets-release.cmake
      DEL /F /Q %INSTALL_DIR%\share\tinyxml\tinyxmlTargets.cmake
      DEL /F /Q %INSTALL_DIR%\include\sdformat-6.2\tinyxml.h
      copy /Y experimental\ros\assimpTargets-release.cmake %INSTALL_DIR%\share\assimp\assimpTargets-release.cmake
      copy /Y experimental\ros\orocos_kdl-config.cmake %INSTALL_DIR%\share\orocos_kdl\orocos_kdl-config.cmake
      copy /Y experimental\ros\python38._pth %INSTALL_DIR%\python38._pth
      copy /Y experimental\ros\extra.pth %INSTALL_DIR%\Lib\site-packages
      copy /Y experimental\ros\pkg-config.exe %INSTALL_DIR%\bin
      copy /Y experimental\ros\glib-2.0.dll %INSTALL_DIR%\bin
  - script: |
      rd /s /q %INSTALL_DIR%\include\kdl
      rd /s /q %INSTALL_DIR%\share\orocos_kdl
      rd /s /q %INSTALL_DIR%\share\orocos-kdl
      DEL /F /Q %INSTALL_DIR%\lib\orocos-kdl.lib
      DEL /F /Q %INSTALL_DIR%\lib\pkgconfig\orocos-kdl.pc
      DEL /F /Q %INSTALL_DIR%\lib\pkgconfig\orocos_kdl.pc
    condition: and(succeeded(), eq(variables.DISTRO_NAME, 'foxy'))
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      set PATH=%INSTALL_DIR%\Scripts;%INSTALL_DIR%;%INSTALL_DIR%\bin;%PATH%
      mkdir catkin_ws\src
      cd catkin_ws
      vcs import --force src < ..\experimental\ros\gazebo.rosinstall
      vcs import src < ..\experimental\ros\ros2.repos
      call ..\experimental\ros\build_foxy.bat
    condition: and(succeeded(), eq(variables.DISTRO_NAME, 'foxy'))
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      set PATH=%INSTALL_DIR%\Scripts;%INSTALL_DIR%;%INSTALL_DIR%\bin;%PATH%
      mkdir catkin_ws\src
      cd catkin_ws
      vcs import --force src < ..\experimental\ros\gazebo.rosinstall
      vcs import --force src < ..\experimental\ros\noetic.rosinstall
      vcs import --force src < ..\experimental\ros\noetic_override.rosinstall
      copy /Y ..\experimental\ros\gazebo\colcon.pkg src\gazebo\gazebo10
      copy /Y ..\experimental\ros\gazebo_dev\colcon.pkg src\gazebo_ros_pkgs\gazebo_dev
      call ..\experimental\ros\build_noetic.bat
    condition: and(succeeded(), eq(variables.DISTRO_NAME, 'noetic'))
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: .\catkin_ws\log
      artifactName: log
    condition: always()
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(INSTALL_DIR)'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
      replaceExistingArchive: true
    condition: always()
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/drop.zip'
      artifactName: drop
    condition: always()
