trigger: none
pr: none

jobs:
- job: Build
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 360
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific' # Options: current, specific
      project: 'ros-win' # Required when source == Specific
      pipeline: 91 # Required when source == Specific
      buildVersionToDownload: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
      artifactName: 'foxy-drop'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)\foxy-drop\*.zip' 
      destinationFolder: 'c:\opt\ros\foxy\x64'
      cleanDestinationFolder: true
  - script: |
      dir c:\opt\ros\foxy\x64
