trigger: none
pr: none

jobs:
- job: Build
  pool: 'Edge-Robotics-VS2019'
  #  vmImage: 'windows-2019'
  timeoutInMinutes: 360
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific' # Options: current, specific
      project: 'ros-win' # Required when source == Specific
      pipeline: 91 # Required when source == Specific
      buildVersionToDownload: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
      artifactName: 'foxy-drop'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)\foxy-drop\*.zip' 
      destinationFolder: 'c:\opt\ros\foxy\x64'
      cleanDestinationFolder: true
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      dir c:\opt\ros\foxy\x64
      set PATH=c:\opt\ros\foxy\x64\Scripts;c:\opt\ros\foxy\x64;c:\opt\ros\foxy\x64\bin;%PATH%
      mkdir catkin_ws\src
      cd catkin_ws
      vcs import src < ..\experimental\ros\ros2.rosinstall
      dir src
      colcon build --event-handlers console_cohesion+ --cmake-args -DBUILD_TESTING:BOOL=False -DCMP0100=NEW -DCMAKE_PROGRAM_PATH=c:\opt\ros\foxy\x64\tools\protobuf;c:\opt\ros\foxy\x64\tools\qt5\bin
