trigger: none
pr: none

jobs:
- job: Setup
  pool:
    vmImage: 'windows-2019'
  variables:
    INSTALL_DIR: 'c:\opt\ros\foxy\x64'
    ROS_DISTRO: 'foxy'
  timeoutInMinutes: 360
  workspace:
    clean: all
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific' # Options: current, specific
      project: 'ros-win' # Required when source == Specific
      pipeline: 103 # Required when source == Specific
      buildVersionToDownload: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
      artifactName: '$(ROS_DISTRO)-setup'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)\$(ROS_DISTRO)-install\install.zip'
      destinationFolder: '$(INSTALL_DIR)'
      cleanDestinationFolder: true
  - powershell: |
      .\experimental\ros\chocolatey\buildChocolatey.ps1 -PackageName "ros-foxy-desktop" -PackageVersion "20200807.0.0.0" -SetupProgram "$Env:System_ArtifactsDirectory\foxy-setup\ros-foxy-setup.exe"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '.\experimental\ros\chocolatey\output'
      artifactName: '$(ROS_DISTRO)-chocolatey'
