trigger: none

variables:
  ROS_DISTRO: 'melodic'
  ROSWIN_METAPACKAGE: 'ros_core'

jobs:
- job: Build
  timeoutInMinutes: 360
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      md C:\opt\ros\melodic\x64
      echo "" > C:\opt\ros\melodic\x64\dummp_test
  - template: package-build.yml
