# maintenance pipeline to delete non-tagged images from a container registry
trigger: none

jobs:
- job: GarbageCollection
  timeoutInMinutes: 240
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: AzureCLI@1
    inputs:
      azureSubscription: $(azureSubscription)
      scriptLocation: 'inlineScript'
      inlineScript: |
        "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ".\docker\garbage-collection.ps1"
    env:
      CONTAINER_REGISTRY: $(containerRegistry)
