trigger: none
pr: none

variables:
  ROSWIN_COLCON_BUILD_WORKING_DIRECTORY: $(Build.SourcesDirectory)\ros-colcon-build

jobs:
- job: Build
  timeoutInMinutes: 300
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    ROSWIN_ROSDEP_LIST_URI: 'https://raw.githubusercontent.com/ms-iot/rosdistro-db/init_windows_py37/rosdep/sources.list.d/10-ms-iot.list'
    ROSWIN_METAPACKAGE: 'ALL'
    ROSWIN_ADDITIONAL_PACKAGE: 'ros_rosdeps'
    ROSWIN_VSTOOL: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
    BUILD_TOOL_PACKAGE: 'ros-colcon-tools'
    PYTHON_LOCATION: 'c:\opt\python37amd64'
  strategy:
    matrix:
      crystal-ros_core:
        ROSWIN_METAPACKAGE: 'ros_core'
        ROS_DISTRO: 'crystal'
        ROS_ETC_DIR: 'c:\opt\ros\crystal\x64\etc\ros'
        ROSWIN_CMAKE_INSTALL_PREFIX: 'c:/opt/ros/crystal/x64'
      crystal-ros_base:
        ROSWIN_METAPACKAGE: 'ros_base'
        ROS_DISTRO: 'crystal'
        ROS_ETC_DIR: 'c:\opt\ros\crystal\x64\etc\ros'
        ROSWIN_CMAKE_INSTALL_PREFIX: 'c:/opt/ros/crystal/x64'
      crystal-desktop:
        ROSWIN_METAPACKAGE: 'desktop'
        ROS_DISTRO: 'crystal'
        ROS_ETC_DIR: 'c:\opt\ros\crystal\x64\etc\ros'
        ROSWIN_CMAKE_INSTALL_PREFIX: 'c:/opt/ros/crystal/x64'
  steps:
  # - template: ..\..\common\agent-clean.yml
  - template: ..\common\checkout.yml
  - template: ..\common\build.yml
  - template: ..\..\package-build\package-build.yml
- job: TestInstall
  dependsOn: Build
  strategy:
    matrix:
      crystal-ros_core:
        ROS_DISTRO: 'crystal'
        ROSWIN_METAPACKAGE: 'ros_core'
  timeoutInMinutes: 300
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: ..\..\package-build\package-test.yml
