trigger: none
pr: none

jobs:
- job: Vcpkg
  pool: Edge-Robotics-VS2022-ESBuild
  timeoutInMinutes: 2000
  strategy:
    matrix:
      x64-windows:
        VCPKG_DEFAULT_TRIPLET: 'x64-windows'
  workspace:
    clean: all
  steps:
  - script: 'reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f'
    displayName: 'Enable long paths on Windows'
  - script: |
      git clone https://github.com/ms-iot/vcpkg.git -b humble
      pushd vcpkg
      set VCPKG_ROOT=%CD%
      set VCPKG_MAX_CONCURRENCY=1
      call ".\bootstrap-vcpkg.bat"
      dir
      .\vcpkg.exe version
      .\vcpkg.exe install tbb:x64-windows
      .\vcpkg.exe install @..\external\humble\vcpkg-ogre.in
      .\vcpkg.exe install @..\external\humble\vcpkg-ogre.in
      popd vcpkg
    continueOnError: true    
  - powershell: |
      & $(Build.Repository.LocalPath)\ros\collectDisclosures.ps1 -Path $(Build.Repository.LocalPath)\vcpkg\buildtrees -outputfile $(Build.Repository.LocalPath)\vcpkg\installed\nav_license.txt
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '.\vcpkg\installed'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/installed.zip'
      replaceExistingArchive: true
    continueOnError: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'D:\a\_work\1\s\vcpkg\buildtrees\tbb\build-x64-windows-dbg-out.log'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/buildtrees.zip'
      replaceExistingArchive: true
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/installed.zip'
      artifactName: '$(VCPKG_DEFAULT_TRIPLET)-installed'
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/buildtrees.zip'
      artifactName: '$(VCPKG_DEFAULT_TRIPLET)-buildtrees'
    continueOnError: true
    
