# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Reset the shell.
SHELL ["cmd", "/S", "/C"]

ADD https://chocolatey.org/install.ps1 C:\TEMP\install.ps1
RUN powershell C:\TEMP\install.ps1 -Wait; Remove-Item C:\TEMP\install.ps1 -Force;

RUN choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1 `
    && choco upgrade git ros-melodic-desktop_full -y `
    && rmdir /q /s %USERPROFILE%\AppData\Local\NuGet\Cache `
    && rmdir /q /s %ChocolateyInstall%\lib

ENTRYPOINT C:\opt\ros\melodic\x64\setup.bat &&
CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
