trigger: none
pr: none

jobs:
- job: Build
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 360
  variables:
    INSTALL_DIR: 'c:\opt\ros\melodic\x64'
  workspace:
    clean: all
  steps:
  - powershell: |
      choco sources add -n=roswin -s https://aka.ms/ros/public --priority 1
      choco upgrade -y --no-progress ros-python2
      choco upgrade -y --no-progress sip
      choco upgrade -y --no-progress eigen
      choco upgrade -y --no-progress tinyxml2
      & .\experimental\external\melodic\copyInstalled.ps1 -InstallDir $Env:INSTALL_DIR
    continueOnError: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(INSTALL_DIR)'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/melodic.zip'
      replaceExistingArchive: true
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/melodic.zip'
      artifactName: melodic-external
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(INSTALL_DIR)/log'
      artifactName: melodic-log
