trigger: none
pr: none

jobs:
- job: Build
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 360
  strategy:
    matrix:
      noetic:
        INSTALL_DIR: 'c:\opt\ros\noetic\x64'
        DISTRO_NAME: 'noetic'
      dashing:
        INSTALL_DIR: 'c:\opt\ros\dashing\x64'
        DISTRO_NAME: 'dashing'
      eloquent:
        INSTALL_DIR: 'c:\opt\ros\eloquent\x64'
        DISTRO_NAME: 'eloquent'
      foxy:
        INSTALL_DIR: 'c:\opt\ros\foxy\x64'
        DISTRO_NAME: 'foxy'
  workspace:
    clean: all
  steps:
  - powershell: |
      & .\experimental\external\bootstrapPython.ps1 -InstallDir $Env:INSTALL_DIR
    continueOnError: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(INSTALL_DIR)'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/python.zip'
      replaceExistingArchive: true
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/python.zip'
      artifactName: $(DISTRO_NAME)-python
