trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - experimental/ros/external/melodic/*
    - experimental/ros/azure-pipelines.external.melodic.yml

jobs:
- job: Build
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 360
  variables:
    INSTALL_DIR: 'c:\opt\ros\melodic\x64'
  workspace:
    clean: all
  steps:
  - powershell: |
      choco sources add -n=roswin -s https://aka.ms/ros/public --priority 1
      & .\experimental\external\melodic\bootstrap.ps1 -InstallDir $Env:INSTALL_DIR
      & .\experimental\external\melodic\vcpkg.ps1 -InstallDir $Env:INSTALL_DIR
    continueOnError: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(INSTALL_DIR)'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/external.zip'
      replaceExistingArchive: true
    continueOnError: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/external.zip'
      artifactName: melodic-external
