trigger: none
pr: none

variables:
  ROSWIN_CATKIN_BUILD_WORKING_DIRECTORY: $(Build.SourcesDirectory)\ros-catkin-build
  ROSWIN_ADDITIONAL_ROSINSTALL: build.rosinstall
  ROSWIN_CMAKE_PREFIX_PATH: 'C:/opt/ros/melodic/x64;C:/opt/rosdeps/x64'

jobs:
- job: Test
  strategy:
    matrix:
      melodic-desktop_full:
        ROSWIN_METAPACKAGE: 'desktop_full'
  timeoutInMinutes: 300
  pool:
    vmImage: 'windows-2019'
  variables:
    ROS_PYTHON_VERSION: '2'
    ROS_DISTRO: 'melodic'
    ROS_ETC_DIR: 'c:\opt\ros\melodic\x64\etc\ros'
    ROSWIN_ROSDEP_LIST_URI: 'https://raw.githubusercontent.com/ms-iot/rosdistro-db/init_windows/rosdep/sources.list.d/10-ms-iot.list'
    ROSWIN_VSTOOL: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
    ROSWIN_PACKAGE_SKIP: 'stage stage_ros'
  steps:
  - template: ..\common\agent-prep.yml
  - template: common\checkout.yml
  - template: common\runtests.yml
