jobs:
- job: Signing
  pool: Edge-Robotics-VS2022-ESBuild
  variables:
    ROS_DISTRO: '${{ parameters.ROS_DISTRO }}'
  timeoutInMinutes: 360
  workspace:
    clean: all
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current' # Options: current, specific
      artifactName: '$(ROS_DISTRO)-setup'
  - task: EsrpCodeSigning@2
    inputs:
      ConnectedServiceName: 'ESRP Signing'
      FolderPath: '$(System.ArtifactsDirectory)\$(ROS_DISTRO)-setup'
      Pattern: '*.exe'
      signConfigType: 'inlineSignParams'
      inlineOperation: |
        [
          {
            "keyCode": "CP-230012",
            "operationSetCode": "SigntoolSign",
            "parameters": [
              {
                "parameterName": "OpusName",
                "parameterValue": "Microsoft"
              },
              {
                "parameterName": "OpusInfo",
                "parameterValue": "http://www.microsoft.com"
              },
              {
                "parameterName": "PageHash",
                "parameterValue": "/NPH"
              },
              {
                "parameterName": "FileDigest",
                "parameterValue": "/fd sha256"
              },
              {
                "parameterName": "TimeStamp",
                "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
              }
            ],
            "toolName": "signtool.exe",
            "toolVersion": "6.2.9304.0"
          }
        ]
      SessionTimeout: '360'
      MaxConcurrency: '50'
      MaxRetryAttempts: '5'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.ArtifactsDirectory)\$(ROS_DISTRO)-setup'
      artifactName: 'ros-$(ROS_DISTRO)-setup-signed'
